services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    environment:
      - CI=true
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    ports:
      - '127.0.0.1:${PORT-3000}:80'
      - '[::1]:${PORT-3000}:80'
